language: node_js
node_js:
  - "8"
sudo: true

services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
script:
- npm run test
- npm run lint
- npm run codecov

cache:
  directories:
    - node_modules
